export const BD_VENDORS = new Set([
  "slot-jili",
  "slot-pgsoft",
  "slot-pragmatic",
  "casino-pragmatic",
  "slot-fachai",
  "slot-jdb",
  "slot-cq9",
  "slot-evoplay",
  "slot-tada",
  "slot-3oaks",
  "slot-habanero",
  "slot-nolimitcity",
  "slot-hacksaw",
  "casino-ezugi",
  "mini-aviator",
  "mini-spribe",
  "mini-inout",
  "mini-bgaming",
  "mini-pragmatic",
  "fishing-jdb",
  "fishing-cq9",
  "fishing-fungaming",
]);

export const BD_FEATURED_VENDORS = [
  "slot-jili",
  "slot-pgsoft",
  "slot-pragmatic",
  "slot-fachai",
  "slot-jdb",
  "slot-cq9",
  "casino-pragmatic",
  "casino-ezugi",
];

export const BD_HOT_GAMES = new Set([
  "slot-jili::super-ace",
  "slot-jili::fortune-gems",
  "slot-jili::golden-empire",
  "slot-jili::boxing-king",
  "slot-jili::money-coming",
  "slot-jili::crazy-777",
  "slot-jili::charge-buffalo",
  "slot-jili::super-ace-deluxe",
  "slot-jili::lucky-coming",
  "slot-jili::wild-ace",
  "slot-jili::mega-ace",
  "slot-pgsoft::fortune-tiger",
  "slot-pgsoft::fortune-ox",
  "slot-pgsoft::fortune-mouse",
  "slot-pgsoft::fortune-rabbit",
  "slot-pgsoft::fortune-dragon",
  "slot-pgsoft::fortune-snake",
  "slot-pgsoft::mahjong-ways",
  "slot-pgsoft::mahjong-ways2",
  "slot-pgsoft::lucky-neko",
  "slot-pgsoft::wild-bandito",
  "slot-pgsoft::treasures-aztec",
  "slot-pragmatic::vs20olympgate",
  "slot-pragmatic::vs20olympx",
  "slot-pragmatic::vs20sugarrush",
  "slot-pragmatic::vs20starlightx",
  "slot-pragmatic::vs25sweetbon",
  "slot-pragmatic::vs20doghouse",
  "slot-pragmatic::vs20fruitswx",
  "slot-pragmatic::vs20rhinoluxe",
  "slot-fachai::super-bingo",
  "slot-fachai::golden-genie",
  "slot-fachai::crazy-buffalo",
  "slot-fachai::chinese-chess",
  "slot-jdb::14001",
  "slot-jdb::14036",
  "mini-aviator::aviator",
  "mini-spribe::mines",
  "mini-spribe::dice",
  "mini-spribe::plinko",
  "mini-spribe::hilo",
  "mini-inout::chicken-road",
  "mini-inout::chicken-road-two",
]);

export function isBDVendor(vendorCode: string): boolean {
  return BD_VENDORS.has(vendorCode);
}

export function isBDHotGame(vendorCode: string, gameCode: string): boolean {
  return BD_HOT_GAMES.has(`${vendorCode}::${gameCode}`);
}
